# Label definitions for OpenSpec workflows
labels:
  # OpenSpec labels
  - name: "spec"
    color: "0E8A16"
    description: "Specification issues"
  - name: "proposal"
    color: "1D76DB"
    description: "Proposal documents"
  - name: "implementation"
    color: "5319E7"
    description: "Implementation pull requests"
  - name: "spec:draft"
    color: "FBCA04"
    description: "Work in progress specs"
  - name: "spec:approved"
    color: "0E8A16"
    description: "Approved and ready for implementation"
  - name: "spec:implemented"
    color: "0B5345"
    description: "Fully implemented specs"
  - name: "needs-spec"
    color: "D93F0B"
    description: "PR missing spec reference"
  - name: "scope-creep"
    color: "B60205"
    description: "Changes beyond spec scope"

  # Existing labels (preserved)
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "security"
    color: "ee0701"
    description: "Security related issues"
  - name: "vulnerability"
    color: "ee0701"
    description: "CVE or vulnerability findings"
